"""create tables

Revision ID: fd26d84d679e
Revises: 
Create Date: 2024-05-19 23:39:37.965384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd26d84d679e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live',
    sa.Column('shakeup_id', sa.String(length=7), nullable=False),
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=4), nullable=False),
    sa.Column('next_stop_id', sa.String(length=5), nullable=False),
    sa.Column('next_stop_departure', sa.DateTime(), nullable=False),
    sa.Column('live_feed_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_table('route',
    sa.Column('shakeup_id', sa.String(length=7), nullable=False),
    sa.Column('route_id', sa.String(length=3), nullable=False),
    sa.Column('route_short_name', sa.String(length=6), nullable=False),
    sa.Column('route_long_name', sa.String(length=256), nullable=False),
    sa.Column('route_group', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('shakeup_id', 'route_id')
    )
    op.create_table('shakeup',
    sa.Column('shakeup_id', sa.String(length=7), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('shakeup_id')
    )
    op.create_table('stop',
    sa.Column('shakeup_id', sa.String(length=7), nullable=False),
    sa.Column('stop_id', sa.String(length=5), nullable=False),
    sa.Column('stop_name', sa.String(length=256), nullable=False),
    sa.Column('stop_name_short', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('shakeup_id', 'stop_id')
    )
    op.create_table('stop_time',
    sa.Column('shakeup_id', sa.String(length=7), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('departure_id', sa.DateTime(), nullable=False),
    sa.Column('stop_id', sa.String(length=5), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('timepoint', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('shakeup_id', 'trip_id', 'stop_id')
    )
    op.create_table('trip',
    sa.Column('shakeup_id', sa.String(length=7), nullable=False),
    sa.Column('route_id', sa.String(length=3), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('trip_headsign', sa.String(length=32), nullable=False),
    sa.Column('block_id', sa.String(length=6), nullable=False),
    sa.Column('rip_headsign_short', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('shakeup_id', 'trip_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('stop_time')
    op.drop_table('stop')
    op.drop_table('shakeup')
    op.drop_table('route')
    op.drop_table('live')
    # ### end Alembic commands ###
