"""fix trip_headsign_short column name

Revision ID: 82ab2683a9c7
Revises: fd26d84d679e
Create Date: 2024-05-20 16:04:06.895986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82ab2683a9c7'
down_revision = 'fd26d84d679e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('trip_headsign_short', sa.String(length=32), nullable=False))
    op.drop_column('trip', 'rip_headsign_short')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('rip_headsign_short', mysql.VARCHAR(length=32), nullable=False))
    op.drop_column('trip', 'trip_headsign_short')
    # ### end Alembic commands ###
