"""reset again because fuck this useless tool

Revision ID: 6266f6b9aca8
Revises: 
Create Date: 2025-04-05 22:05:43.310031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6266f6b9aca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_shapes', schema=None) as batch_op:
        #batch_op.alter_column('int_shape_id',
        #       existing_type=sa.INTEGER(),
        #       server_default=None,
        #       type_=sa.SmallInteger(),
        #       existing_nullable=False,
        #       autoincrement=True)
        batch_op.alter_column('shape_length',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)

    with op.batch_alter_table('static_stop_times', schema=None) as batch_op:
        batch_op.alter_column('shape_dist_traveled',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)

    with op.batch_alter_table('static_trips', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'static_shapes', ['int_shape_id'], ['int_shape_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_trips', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('static_stop_times', schema=None) as batch_op:
        batch_op.alter_column('shape_dist_traveled',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('static_shapes', schema=None) as batch_op:
        batch_op.alter_column('shape_length',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('int_shape_id',
               existing_type=sa.SmallInteger(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
