"""remove trips/shapes relationships because I'm not intelligent enough to implement them

Revision ID: 885f99ab7c96
Revises: 6266f6b9aca8
Create Date: 2025-04-05 22:21:23.231249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885f99ab7c96'
down_revision = '6266f6b9aca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    #with op.batch_alter_table('static_shapes', schema=None) as batch_op:
    #    batch_op.alter_column('int_shape_id',
    #           existing_type=sa.INTEGER(),
    #           type_=sa.SmallInteger(),
    #           existing_nullable=False,
    #           autoincrement=True)
    #    batch_op.alter_column('shape_length',
    #           existing_type=sa.REAL(),
    #           type_=sa.Float(precision=3),
    #           existing_nullable=False)

    with op.batch_alter_table('static_stop_times', schema=None) as batch_op:
        batch_op.alter_column('shape_dist_traveled',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)

    with op.batch_alter_table('static_trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shape_id', sa.Text(), nullable=False))
        batch_op.drop_column('int_shape_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('int_shape_id', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.drop_column('shape_id')

    with op.batch_alter_table('static_stop_times', schema=None) as batch_op:
        batch_op.alter_column('shape_dist_traveled',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('static_shapes', schema=None) as batch_op:
        batch_op.alter_column('shape_length',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('int_shape_id',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
